name: Build & Deploy Eureka & Api Gateway

on:
  push:
    branches: [ "backend", "main" ]
    paths:
      - 'backend/ms-discovery/**'
      - 'backend/ms-gateway/**'
  pull_request:
    branches: [ "backend", "main" ]
    paths:
      - 'backend/ms-discovery/**'
      - 'backend/ms-gateway/**'

jobs:
  config-aws:
    name: Config AWS credentials
    runs-on: ubuntu-latest
    steps:
      
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
        
  build-eureka-and-gateway:
    needs: config-aws
    name: Build Eureka & Gateway with Maven
    runs-on: ubuntu-latest      
    steps:
            
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
        
    - name: Configure SSH Key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.DEPLOY_KEY_EUREKA_GATEWAY }}" > ~/.ssh/id_rsa
        chmod 400 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.DEPLOY_SERVER_IP_EUREKA_GATEWAY }} >> ~/.ssh/known_hosts
      env:
        HOST: ${{secrets.DEPLOY_SERVER_IP_EUREKA_GATEWAY}}

    - name: Build Eureka
      run: |
        echo "Building app..."
        cd backend/ms-discovery
        mvn install --file pom.xml
        echo "Finished building the app."
        
    - name: Build Gateway
      run: |
        echo "Building app..."
        cd backend/ms-gateway
        mvn install --file pom.xml
        echo "Finished building the app."

    - name: Deploy Eureka
      run: |
        echo "Deploying started..."
        ssh ubuntu@${HOST} "sudo systemctl stop eureka.service"
        scp ms_discovery.jar ubuntu@${HOST}:~/app/eureka
        ssh ubuntu@${HOST} "sudo systemctl start eureka.service"
        echo "Finished deploying the app."
      working-directory: /home/runner/work/Me-Sumo/Me-Sumo/backend/ms-discovery/target
      env:
        HOST: ${{secrets.DEPLOY_SERVER_IP_EUREKA_GATEWAY}}
              
    - name: Deploy Api Gateway
      run: |
        echo "Deploying started..."
        ssh ubuntu@${HOST} sudo systemctl stop gateway.service
        scp ms_gateway.jar ubuntu@${HOST}:~/app/gateway
        # scp ms_gateway.jar ubuntu@${HOST}:~/app/gateway
        ssh ubuntu@${HOST} sudo systemctl start gateway.service
        echo "Finished deploying the app."
      working-directory: /home/runner/work/Me-Sumo/Me-Sumo/backend/ms-gateway/target
      env:
        HOST: ${{secrets.DEPLOY_SERVER_IP_EUREKA_GATEWAY}}