name: Upload Website

on:
  push:
    branches: [ "main", "frontend" ]
    paths:
      - 'frontend/**'
  pull_request:
    branches: [ "main", "frontend" ]
    paths:
      - 'frontend/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Change to frontend directory
        run: cd frontend

      - name: Set up Node.js
        uses: actions/setup-node@v2

      - name: Install dependencies
        run: npm install
        working-directory: ./frontend

      - name: Build app
        run: npm run build
        working-directory: ./frontend

      - name: Set AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      
      - name: Copy to S3
        run: aws s3 sync dist/ s3://me-sumo-frontend
        working-directory: ./frontend
