name: Build & Deploy MS Bookings

on:
  push:
    branches: [ "backend", "main" ]
    paths:
      - 'backend/ms-bookings/**'
  pull_request:
    branches: [ "backend", "main" ]
    paths:
      - 'backend/ms-bookings/**'

jobs:
  config-aws:
    name: Config AWS credentials
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

  build-booking:
    needs: config-aws
    runs-on: ubuntu-latest
    steps:
          
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Build MS Booking
      run: |
        echo "Building app..."
        cd backend/ms-bookings
        mvn install --file pom.xml
        echo "Finished building the app."

    - name: Archive Booking Build
      uses: actions/upload-artifact@v3
      with:
        name: bookings
        path: backend/ms-bookings/target/ms_bookings.jar

  deploy-booking: 
    needs: build-booking
    name: Deploy MS Booking
    runs-on: ubuntu-latest
    steps: 

    - name: Download Booking Build Artifact
      uses: actions/download-artifact@v3
      with:
        name: bookings
    
    - name: Configure SSH Key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.DEPLOY_KEY_BOOKING }}" > ~/.ssh/id_rsa
        chmod 400 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.DEPLOY_SERVER_IP_BOOKING }} >> ~/.ssh/known_hosts
      env:
        HOST: ${{ secrets.DEPLOY_SERVER_IP_BOOKING }}
        
    - name: Deploy Booking
      run: |
          echo "Deploying started..."
          ssh ubuntu@${HOST} sudo systemctl stop booking.service
          scp ms_bookings.jar ubuntu@${HOST}:~/booking
          ssh ubuntu@${HOST} sudo systemctl start booking.service
          echo "Finished deploying the app."
      env:
          HOST: ${{ secrets.DEPLOY_SERVER_IP_BOOKING }}
